### ISSUE TITLE
The demo page returns a 404.

### ISSUE THREAD

**Issue by josephdburdick** [amazingBastard/orion-semantic-ui#1]
This link found in the README http://orion-semantic-ui.meteor.com doesn't return a demo page.

**Comment by dvzrd** [comment]
Sorry,

I'm still working on the demo page. Should be up later today. I'll update you here when it's live. Thanks.

**Comment by dvzrd** [comment]
Here's a link to a working version: http://orion-semantic-ui.meteor.com/

I notice there's a bunch of things I need to fix to the package so I'll be making those soon.

**Comment by josephdburdick** [comment]
Cool! Thanks, you @amazingBastard.
