### ISSUE TITLE
Do nested links work?

### ISSUE THREAD

**Issue by chmac** [amazingBastard/orion-semantic-ui#3]
When I try adding a nested link, I can see the links if I inspect the elements, but the menu itself is broken. There's no way to click the arrow and reveal the sub menu. I just tried switching out to bootstrap and it works there.

CC @sarasate

**Comment by dvzrd** [comment]
I'll need to recreate the issue. Do you have an example of the issue I can look at? I may need to use the semantic version of collapse to show the sub menu which I might have overlooked.

**Comment by chmac** [comment]
Don't have a reproduction to hand, but will try to work on one tomorrow if I get a chance...

**Comment by dvzrd** [comment]
No problem, In the meantime, I'll modify the sidebar a bit and see if that fixes it. Keep me updated.

**Comment by dvzrd** [comment]
I moved the dropdown call to the actual template that has the dropdown class. Let me know if that changed anything.

**Comment by chmac** [comment]
[Here's](https://github.com/superlumen/orion-semantic) a reproduction. Doesn't look like 0.6.2 has fixed the issue.

**Comment by dvzrd** [comment]
@chmac, the collapse/accordion should be working with the latest version. Thanks for helping me debug this with the repo.
