### ISSUE TITLE
How to style?

### ISSUE THREAD

**Issue by ghost** [amazingBastard/orion-semantic-ui#4]
I am wondering if there is a way to customize the admin by using the semantic ui classes and code?  Or can I only do that vis-a-vis CSS?

Thanks,

Moshe

**Comment by dvzrd** [comment]
Hey,

You can clone the repo, and add the package (create a packages dir) into your project and customize it from there. 

If you do this, make sure to remove the old package and add your local package (give it a different name in package.js).

Let me know what you want to customize, maybe we can add it to the package with a pull request.
